### ISSUE TITLE
How to create secret key like this

### ISSUE THREAD

**Issue by hendisantika** [ali-bouali/spring-boot-3-jwt-security#59]
How to create secret key like this?

```
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
```

Suppose I have secret key like this: `verytopsecret`?

Thanks
